spring.application.name=consig-facil-3
server.servlet.context-path=/api/v1

# application.properties
spring.datasource.url=jdbc:postgresql://db:5432/consig_db
spring.datasource.username=${DB_USER:consig_user}
spring.datasource.password=${DB_PASSWORD:consig_password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Permite que migrations atrasadas de outras branches rodem sem quebrar o build
spring.flyway.out-of-order=true
api.security.token.secret=${JWT_SECRET:49673836344274714C626F304753554D6E667167683930414E5A445258324F53}
